# Generated by Django 3.0.8 on 2020-07-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic_link", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclink",
            name="logged_in_at",
            field=models.DateTimeField(
                blank=True, help_text="When the link was used to login", null=True
            ),
        ),
    ]
