# Generated by Django 3.0.8 on 2020-07-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magic_link", "0002_magiclink_logged_in_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclink",
            name="accessed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the link was first used (GET)", null=True
            ),
        ),
    ]
