# Generated by Django 3.0.8 on 2020-07-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magic_link", "0003_magiclink_accessed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="magiclinkuse",
            name="link_is_valid",
        ),
    ]
