# Generated by Django 4.1.4 on 2023-12-02 14:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("magic_link", "0004_remove_magiclinkuse_link_is_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="token",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique login token",
                max_length=36,
                unique=True,
            ),
        ),
    ]
